CREATE TABLE IF NOT EXISTS "treatment_types" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL UNIQUE,
	"displayName" text,
	"isActive" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);

-- Insert default treatment types
INSERT INTO "treatment_types" ("name", "displayName", "isActive") VALUES
	('12-unit bridge', '12-Unit Bridge', true),
	('3 unit zirconia bridge', '3 Unit Zirconia Bridge', true),
	('8 unit zirconia bridge', '8 Unit Zirconia Bridge', true),
	('acrylic bridge', 'Acrylic Bridge', true),
	('acrylic crown', 'Acrylic Crown', true),
	('acrylic denture 2 unit', 'Acrylic Denture 2 Unit', true),
	('acrylic denture 3 unit', 'Acrylic Denture 3 Unit', true),
	('acrylic denture(ant. + post. teeth)', 'Acrylic Denture(Ant. + Post. Teeth)', true),
	('acrylic denture(anterior 2-4 teeth)', 'Acrylic Denture(Anterior 2-4 Teeth)', true),
	('acrylic denture(anterior 5-6 teeth)', 'Acrylic Denture(Anterior 5-6 Teeth)', true),
	('acrylic denture(full arch)', 'Acrylic Denture(Full Arch)', true),
	('acrylic denture(posterior teeth)', 'Acrylic Denture(Posterior Teeth)', true),
	('acrylic denture(single tooth)', 'Acrylic Denture(Single Tooth)', true),
	('biopsy', 'Biopsy', true),
	('bone filling', 'Bone Filling', true),
	('braces removal', 'Braces Removal', true),
	('braces-one jaw', 'Braces-One Jaw', true),
	('composit filling(veneer)', 'Composit Filling(Veneer)', true),
	('composite filling(spot)', 'Composite Filling(Spot)', true),
	('crown(acrylic)', 'Crown(Acrylic)', true),
	('crown(porcelain fused to metal)', 'Crown(Porcelain Fused To Metal)', true),
	('dental consultation', 'Dental Consultation', true),
	('denture repair', 'Denture Repair', true),
	('digital/gauze aided extraction', 'Digital/Gauze Aided Extraction', true),
	('fixed ortho appliance(both jaws)-braces', 'Fixed Ortho Appliance(Both Jaws)-Braces', true),
	('fluoride therapy', 'Fluoride Therapy', true),
	('forceps extraction', 'Forceps Extraction', true),
	('four unit pfm bridge', 'Four Unit Pfm Bridge', true),
	('functional appliance', 'Functional Appliance', true),
	('gic filling per quadrant', 'Gic Filling Per Quadrant', true),
	('gingivecitomy/gingival cotouring', 'Gingivecitomy/Gingival Cotouring', true),
	('glass ionomer filling', 'Glass Ionomer Filling', true),
	('glass lonomer cement filling + composite filling', 'Glass Lonomer Cement Filling + Composite Filling', true),
	('hawleys removable appliance', 'Hawleys Removable Appliance', true),
	('imf surgery', 'Imf Surgery', true),
	('imf suturing', 'Imf Suturing', true),
	('implant', 'Implant', true),
	('incision and drainage', 'Incision And Drainage', true),
	('lingual arch', 'Lingual Arch', true),
	('operculectomy', 'Operculectomy', true),
	('orthodontic retainer-thermoplastic', 'Orthodontic Retainer-Thermoplastic', true),
	('periapical xray', 'Periapical Xray', true),
	('pfm bridge', 'Pfm Bridge', true),
	('post', 'Post', true),
	('post insertion+crown', 'Post Insertion+Crown', true),
	('pulpectomy', 'Pulpectomy', true),
	('pulpotomy', 'Pulpotomy', true),
	('recementation of crown', 'Recementation Of Crown', true),
	('reconstruction/composite filling', 'Reconstruction/Composite Filling', true),
	('redo of root canal therapy(anterior tooth)', 'Redo Of Root Canal Therapy(Anterior Tooth)', true),
	('repaire retainer', 'Repaire Retainer', true),
	('retainer', 'Retainer', true),
	('ortho review', 'Ortho Review', true),
	('root canal therapy', 'Root Canal Therapy', true),
	('root canal therapy + crown', 'Root Canal Therapy + Crown', true),
	('root canal therapy and zirconia crown', 'Root Canal Therapy And Zirconia Crown', true),
	('root canal therapy(anterior tooth)', 'Root Canal Therapy(Anterior Tooth)', true),
	('root canal therapy(molar tooth)', 'Root Canal Therapy(Molar Tooth)', true),
	('root canal therapy(premolar tooth)', 'Root Canal Therapy(Premolar Tooth)', true),
	('root canal treatment', 'Root Canal Treatment', true),
	('root canal treatment + crown', 'Root Canal Treatment + Crown', true),
	('scaling and polishing', 'Scaling And Polishing', true),
	('scaling and polishing + root plaining', 'Scaling And Polishing + Root Plaining', true),
	('six -units pfm bridge', 'Six -Units Pfm Bridge', true),
	('splinting of tooth(per 2 teeth)', 'Splinting Of Tooth(Per 2 Teeth)', true),
	('surgical extraction', 'Surgical Extraction', true),
	('suturing', 'Suturing', true),
	('themoplast retainer', 'Themoplast Retainer', true),
	('three-units pfm bridge', 'Three-Units Pfm Bridge', true),
	('tilite bridge', 'Tilite Bridge', true),
	('tilite bridge 6 unit', 'Tilite Bridge 6 Unit', true),
	('tooth gem', 'Tooth Gem', true),
	('two-units pfm bridge', 'Two-Units Pfm Bridge', true),
	('valplast denture 1 unit', 'Valplast Denture 1 Unit', true),
	('valplast denture 2 unit', 'Valplast Denture 2 Unit', true),
	('valplast denture 4 unit', 'Valplast Denture 4 Unit', true),
	('valplast denture 8 unit upper 5 unit lower', 'Valplast Denture 8 Unit Upper 5 Unit Lower', true),
	('valplast denture(ant. + post.)', 'Valplast Denture(Ant. + Post.)', true),
	('valplast denture(anterior)', 'Valplast Denture(Anterior)', true),
	('valplast denture(posterior)', 'Valplast Denture(Posterior)', true),
	('whitening/bleaching(full mouth)', 'Whitening/Bleaching(Full Mouth)', true),
	('x-ray', 'X-Ray', true),
	('zirconia crown', 'Zirconia Crown', true)
ON CONFLICT ("name") DO NOTHING;
