import { db } from '@/lib/db'
import { patients } from '@/lib/db/schema'
import { sql } from 'drizzle-orm'

const orthoPatientNames = [
    'Abena Kwartemaa',
    'Lordina Antwi-Afriyie',
    'Evelyn Pokuaa Frimpomg',
    'Sabbathina Bodu Dapaah',
    'Abigail Kumi Asante',
    'Anastasia Osei',
    'Mawuana Gamel zigah',
    'Fauzia Ofori',
    'Rita Appiah',
    'Oheneba Afriyie',
    'Kendra Abena Fosuaa Dampare',
    'Lawrencia Amafo Ofori',
    'Patience Ozonsi',
    'Abigail Asamoah karikari',
    'Daniel kwakye Mensah',
    'Grace Darko Adu',
    'Sadick Moro',
    'Frankly Osei Owusu',
    'Juanita Okyerewaa Afum',
    'Dorcas Obeng',
    'Theo Derrick Aidoo',
    'Samuel Amankwah',
    'Esther Adwubi',
    'Mussa Salisu',
    'Mavis Ama Anane',
    'Philipa Anane',
    'Kindra Doodo',
    'Nicholas Doodu',
    'Flora osei pomaa',
    'Jacinta Akaadom',
    'Akosua Kyerewaa Kwarteng',
    'Yaw Boatey',
    'Erica Owusuwaa Akoto',
    'Frank Acheampong',
    'Nana Akua Sarpong',
    'Blessing Afriyie Gyan',
    'Celestina Fordjour',
    'Pearl Mawutor Avemee',
    'Aurora Meier',
    'Zack Rahman',
    'Christiana Poku Baffour',
    'Daisy Buckman',
    'Francis Ekow Mensah',
    'Belinda Tawiah',
    'Micheal Yaw Gyamera',
    'Augustina Konadu Mawuli',
    'Audrey Gyasi Effah',
    'Bernice Amoakohene',
    'Lisa Achiaa Nkansa-Ninwie',
    'Daniella Dushie',
    'Scholastic Mangame',
    'Philipa Nana Akua Baako',
    'Stelliam Osei Bonsu',
    'Eliana Akomaa Darko',
    'Naa Nuertekie Noye',
    'Abena Dapaah',
    'Sarah Boateng',
    'Jacqueline Antwi',
    'Aduboafo Kwadwo Boateng',
    'Esther Yao Agbetor',
    'Bridget Abena Nyame Afriyie',
    'Margarte Anyele',
    'Maame Ama Agyeiwaa Opoku',
    'Samira Umar',
    'Emerald Berchie',
    'Cecilia  Atotarege',
    'Tracy Oduro Yeboah',
    'Charles Opare',
    'Alexander Atta Bonsu',
    'Linda Annor',
    'Margarete Arhin Sarfo',
    'Peniel Korantemaa Brempong',
    'Marvin Boateng Agyemang',
    'Leoney Agyei Mensah',
    'Yaa Knonadu Oppong',
    'Naomi Nuamah',
    'Esther Boaduwaa Opoku',
    'Benedicta Amoah Mensah',
    'Dora Adeetuk',
    'Rebecca Osei Owusu',
    'Andrews Sosu Senayah',
    'Emelia Sekyere Nyarko',
    'Jason Asare Druye',
    'Stanley Kelven Ekow Gand',
    'Nina Agyei Nomafo',
    'Mercy Asare Kwarteng',
    'Alice Awuku',
    'Jacqueline Amoakowaa Dadzie',
    'Victor Owusu Sarpong',
    'Christabel Mensah',
    'Eric Osei Ntasah',
    'Samuel Owusu',
    'Elizabeth Osei Kwarteng',
    'Franka Amankwah',
    'Cynthia Sarpong',
    'Blessing O.A.Agyapong',
    'Abigail Adjei',
    'Clinton Yeboah Junior',
    'Egbert Addai',
    'Nancy Obeng Manu',
    'STANLEY KUSI APPIAH',
    'NANA AKUA FRIMPOMAA',
    'REGINA DOMFEH',
    'PEREZ FRIMPONG DANSO',
    'MARY BEDIAKO OPOKU',
    'NICK KUSI DANSO',
    'EVELYN E. AKOSUA FIADZO',
    'AKWASI BOAMAH OKYERE',
    'PADMOND BAIDOO',
    'BLESSING ADUSEI AGYEI',
    'LADY BAIDOO',
    'KAREN -HAPPOCH GYASI-DARKO',
    'NANA YAW OFORI ACHEAMPONG',
    'ADWOA SERWAA OWUSU',
    'EVANDY ABENA AGYEMANG',
    'GLORY AGYEMANG DUAH',
    'HELINA BEMAH',
    'MERCIA YAA ODURAA ADU',
    'KOFI OSEI SARKODIE',
    'CHRISTABLE AMMA ANTWIAAH',
    'SETH GYASI ANKAMAH',
    'LOVIA DUROWAA ASARE',
    'RANSFORD SIAW TWUMASI',
    'KOFI OTU',
    'YAA YEBOAH FRIMPONG',
    'ABENA KONADU AGYEMANG',
    'ANASTASIA FLORENCE MUSSEY',
    'REBECCA AFIA NIPAH',
    'ELIJAH GYAMFI',
    'ABENA BOATEMAA',
    'GIFTY MENSAH BONSU',
    'AUGUSTINA OWUSUAA',
    'MAGDALINE OSEI DANSO',
    'RICHLOVE SAKYI BAIDEN',
    'ANGELA ABRAFI YEBOAH',
    'FREDRICA ABA WOODEN',
    'STANLEY OPOKU',
    'PHILIPA OPOKU',
    'GLORIA KESEWAA',
    'KIERA BERTHA ADJEI YEBOAH',
    'JACQUELINE OKOH LARTEY',
    'DORIS ACHEAMPONG',
    'KOFI AMPONG',
    'SYLVESTER AGYEMANG',
    'BASIT NASIR SUNG',
    'PERSIS CHARLOTTE OWUSU',
    'BRIGHTINA DARKOAA',
    'YVONNE EVA OSEI',
    'SHARON KUFFOUR',
    'FESTUS YAW ARMOH',
    'JOEL APRAKU BECHIE',
    'OHENEBA KWABENA ATUAHENE',
    'PETRA ACHIAA ADDAI',
    'PRISCILLA OPPONG',
    'JESUSSAH ASHIA',
    'COMFORT OWUSU',
    'ANNIE DUGAN',
    'PRISCILLA ACHEAMPONG',
    'EMMANUEL OPOKU-AMO',
    'JOHN GRANT BENTUM',
    'DANIELLA BROBBEY',
    'MERCY OWUSU',
    'PRISCILLA OSEI',
    'AMA NHYIRA A.ARTHUR',
    'BENNY YAMOAH-GHANSAH',
    'DIANA BOAKYE YIADOM',
    'ROBERTA  ACHEAMPONG',
    'STEPHANY DWOMOH',
    'FRANK BOAKYE',
    'OWUSU AFRIYIE BOAHEN',
    'BENEDICT KWASI OWUSU',
    'MAAME AMA AGYAPOMAA',
    'ABENA BOATEMAA BERKO',
    'AFIA AGYEMANG BERKO',
    'AKUA TWUMWAA BUSIA',
    'VIVIAN ADU OPOKU',
    'RYAN ADJETEY SOWAH',
    'OSAAH KYEI KANKAM',
    'WINSTON OWUSU ANSAH',
    'CHRISTIANA BOAMAH',
    'ABENA ACHIAA BOATENG',
    'ZENORA ANTWI',
    'KWAME ANIAGYEI',
    'BEATRICE NTRIWAA APPEATU',
    'CHARLOTTE YAA BEMA',
    'GIFTY OSEI AFRIYIE',
    'JENNIFER AWEREWAA',
    'DIANA MILLS',
    'PEARL KOTOKA',
    'ANNELLE OPPONG AMANKWAH',
    'CHARLOTTE SERWAA ASIEDU',
    'JOSEPH HAYFORD NKETIAH',
    'JEMIMA MANU-ADABOR',
    'ADWOA SERWAA AGYEPONG',
    'NANA KWADWO AGYEPONG',
    'ROSETTE MANU-ADABOR',
    'GEORGINA KUMI',
    'GEORGINA AKAKPO',
    'KENNETH SARPONG',
    'DEBORAH MENSAH',
    'FELIX OWUSU ASIEDU',
    'AFIA KOBI',
    'ABIGAIL MENSAH',
    'MERCY ODEY',
    'SAMUEL AMANKWAH',
    'DR. ERNEST KISSI',
    'NANA ABENA M. ADWOBOAH',
    'MOSES SAMBIAN',
    'STACY SOSU SENYAH',
    'DESMOND ADDAI',
    'KWADWO NKUM BITIHENE',
    'JOSEPHINE OPOKU',
    'BRIGHT  BIOH',
    'DAVID OPUNI FRIMPONG',
    'JOWICA FRIMPONG',
    'SAMUEL NANA O.FRIMPONG',
    'DOREEN OWUSUAA ABOAGYE',
    'ISABEL ANNANG',
    'DR. RICHMOND BADU',
    'ONEIL OPOKU GYAMERAH',
    'NANA AFIA SEREBOUR',
    'KWADWO MARFO ANTWI',
    'BLESSING AFRIFA',
    'GLORIA OPPONG PREMPEH',
    'THOMAS BOAKYE',
    'AKOSUA OWUSU PINAMANG',
    'YAW ADOMAKO',
    'GIFTY QUARM',
    'HANNAH OSEI',
    'STEPHEN ASARE',
    'GRACECY BOSSMAN ASANTE',
    'PORTIA YEBOAH',
    'EMMANUELLA OWUSU',
]

async function updateOrthoPatients() {
    console.log(`Starting case-insensitive update for ${orthoPatientNames.length} patients...`)

    let updated = 0
    let notFound = 0

    for (const name of orthoPatientNames) {
        try {
            // Use case-insensitive matching with LOWER()
            const result = await db
                .update(patients)
                .set({ isOrtho: true })
                .where(sql`LOWER(${patients.name}) = LOWER(${name})`)

            if (result.rowCount && result.rowCount > 0) {
                updated++
                console.log(`✓ Updated: ${name}`)
            } else {
                notFound++
                console.log(`✗ Not found: ${name}`)
            }
        } catch (error) {
            console.error(`Error updating ${name}:`, error)
        }
    }

    console.log(`\nUpdate complete!`)
    console.log(`Updated: ${updated}`)
    console.log(`Not found: ${notFound}`)
    console.log(`Total: ${orthoPatientNames.length}`)
}

updateOrthoPatients()
    .then(() => {
        console.log('Script finished successfully')
        process.exit(0)
    })
    .catch((error) => {
        console.error('Script failed:', error)
        process.exit(1)
    })
